// src/components/layout/Footer.vue
<script setup>
import Button from "@/components/common/Button.vue";
</script>

<template>
  <footer class="bg-[#2B2B2B] w-full h-96 flex justify-center p-8 px-12">
    <div class="w-4/5 flex flex-col gap-14 justify-around">
      <div class="flex justify-between">
        <div class="flex flex-col gap-5">
          <div>
            <img class="mb-2" src="/src/assets/images/icons/logo-svgrepo.svg" alt="logo">
            <b class="text-[#F8F8F8]">CARGO PRO</b>
          </div>
          <div>
            <div class="mb-2">
              <h2 class="text-[#F8F8F8] font-bold">Подпишитесь на рассылку</h2>
              <p class="text-[#D7D7D7]">Мы будем отправлять вам полезную информаю раз в неделю</p>
            </div>
            <div class="flex gap-3">
              <input class="w-72 outline-none p-2 rounded-lg" placeholder="Ваш email" type="text"/>
              <Button>Отправить</Button>
            </div>
          </div>
        </div>
        <div class="flex justify-between text-[#AFAFAF] gap-16 items-center mr-20">
          <div class="flex flex-col gap-3 mt-3">
            <a class="hover:opacity-75" href="#"><b>Компания</b></a>
            <a class="hover:opacity-75" href="#">О нас</a>
            <a class="hover:opacity-75" href="#">Карьера</a>
            <a class="hover:opacity-75" href="#">Новости</a>
            <a class="hover:opacity-75" href="#">Контакты</a>
          </div>
          <div class="flex flex-col gap-3">
            <a class="hover:opacity-75" href="#"></a><b>Информация</b>
            <a class="hover:opacity-75" href="#">Правила</a>
            <a class="hover:opacity-75" href="#">Защита данных</a>
            <a class="hover:opacity-75" href="#">Cookies</a>
            <a class="hover:opacity-75" href="#">Настройки</a>
          </div>
          <div class="flex flex-col gap-3">
            <a class="text-white hover:opacity-75" href="#"></a><b>Ресурсы</b>
            <a class="hover:opacity-75" href="#">Блог</a>
            <a class="hover:opacity-75" href="#">Мероприятия</a>
            <a class="hover:opacity-75" href="#">Центр помощи</a>
            <a class="hover:opacity-75" href="#">Поддержка</a>
          </div>
        </div>
      </div>
      <div class="border-t border-gray-500 flex">
        <div class="flex justify-between px-5 text-center items-center mt-5 w-full">
          <div>
            <p class="text-[#D7D7D7]">© 2023 CARGO PRO. Все права защищены.</p>
          </div>
          <div class="flex gap-5">
            <img class="cursor-pointer hover:opacity-75" src="/src/assets/images/icons/contacts/twitter.svg"
                 alt="twitter">
            <img class="cursor-pointer hover:opacity-75" src="/src/assets/images/icons/contacts/link.svg" alt="link">
            <img class="cursor-pointer hover:opacity-75" src="/src/assets/images/icons/contacts/facebook.svg"
                 alt="facebook">
          </div>
        </div>
      </div>
    </div>
  </footer>
</template>

// app/components/footer/footer.tsx
import Link from 'next/link'
import Image from 'next/image'

const Footer = () => {
	return (
		<footer className='bg-[#2B2B2B]'>
			<div className='_container h-[439px] py-[41px] flex flex-col justify-between max-w-c-full m-auto w-full'>
				<div className='flex items-center justify-between'>
					<div>
						<div className='h-[30px] w-[150px] mb-2'>
							<Image
								className='h-full w-full'
								src='/logo.svg'
								alt='Asiafy'
								width={110}
								height={23}
							/>
						</div>
						<div className=' mb-[29px] font-bold text-lg text-white'>
							ASIAFY
						</div>
						<div className=' font-semibold text-lg text-white mb-1'>
							Подпишитесь на рассылку
						</div>
						<div className=' mb-4 font-medium text-[#D7D7D7] text-base'>
							Мы будем отправлять вам полезную информаю раз в неделю
						</div>
						<div className='flex'>
							<input
								className=' h-12 w-[280px] rounded-lg px-4 py-3 font-medium text-[16px] mr-4'
								type='text'
								placeholder='Ваш email'
							/>
							<button>
								<div className=' font-semibold text-white text-base w-fit'>
									Отправить
								</div>
							</button>
						</div>
					</div>
					<div className='grid grid-cols-[1fr_1fr_1fr] gap-[100px]'>
						<div>
							<div className='mb-4 text-white font-semibold text-sm'>
								Компания
							</div>
							<nav>
								<ul>
									<li className=' font-medium text-[#AFAFAF] mb-4'>О нас</li>
									<li className=' font-medium text-[#AFAFAF] mb-4'>Карьера</li>
									<li className=' font-medium text-[#AFAFAF] mb-4'>Новости</li>
									<li className=' font-medium text-[#AFAFAF]'>Контакты</li>
								</ul>
							</nav>
						</div>
						<div>
							<div className='mb-4 text-white font-semibold text-sm'>
								Компания
							</div>
							<nav>
								<ul>
									<li className=' font-medium text-[#AFAFAF] mb-4'>О нас</li>
									<li className=' font-medium text-[#AFAFAF] mb-4'>Карьера</li>
									<li className=' font-medium text-[#AFAFAF] mb-4'>Новости</li>
									<li className=' font-medium text-[#AFAFAF]'>Контакты</li>
								</ul>
							</nav>
						</div>
						<div>
							<div className='mb-4 text-white font-semibold text-sm'>
								Компания
							</div>
							<nav>
								<ul>
									<li className=' font-medium text-[#AFAFAF] mb-4'>О нас</li>
									<li className=' font-medium text-[#AFAFAF] mb-4'>Карьера</li>
									<li className=' font-medium text-[#AFAFAF] mb-4'>Новости</li>
									<li className=' font-medium text-[#AFAFAF]'>Контакты</li>
								</ul>
							</nav>
						</div>
					</div>
				</div>
				<div className='p-[20px] border-t border-[#7A7A7A] flex items-center justify-between'>
					<div className='font-medium text-[#D7D7D7]'>
						© 2023 ASIAFY. Все права защищены.
					</div>
					<div>
						<ul className='flex'>
							<li className='mr-6'>
								<Image src='/logo.svg' alt='123' width={110}
								height={23}/>
							</li>
							<li className='mr-6'>
								<Image src='/logo.svg' alt='123' width={110}
								height={23}/>
							</li>
							<li>
								<Image src='/logo.svg' alt='123' width={110}
								height={23}/>
							</li>
						</ul>
					</div>
				</div>
			</div>
		</footer>
	)
}

export default Footer
